export const APP_BAR_ACTION_SET_ACTION = 'APP_BAR_ACTION_SET_ACTION'
export const APP_BAR_ACTION_DELETE_ACTION = 'APP_BAR_ACTION_DELETE_ACTION'
export const APP_BAR_ACTION_CLEAR_ACTION = 'APP_BAR_ACTION_CLEAR_ACTION'
export const APP_BAR_ACTION_POSITION_MAIN = 'main'
export const APP_BAR_ACTION_POSITION_MORE = 'more'

